### ISSUE TITLE
Could you please provide the kitti dataset?

### ISSUE THREAD

**Issue by jiachen0212** [ayziksha/DSIN#1]
hello ayziksha, 
        First of all, thank you very much for your work and gave me great inspiration. I was trying to learn your code, and then I ran into a problem that the KITTI dataset could not be downloaded. So could you please provide a link to a data set such as a cloud disk or something? Thank you very much~

**Comment by ayziksha** [comment]
Dear jiachen0212,
Thank you for your interest in our work. The KITTI data set is comprised from the official data-sets KITTI2015 and KITTI2012. In order to download each one, after clicking on the links provided in the 'read-me', you will be requested to provide your email and a download link will be sent to you. 
Good luck.

**Comment by jiachen0212** [comment]
@ayziksha  Thanks for your reply, I got the data download link by email, but the link doesn't support the Chinese network, I can't get KITTI data...so sad...

**Comment by ayziksha** [comment]
Dear jiachen0212,
You can try contacting the KITTI dataset publisher or someone you know might hold a copy?
Also, you can try using VPN.

**Comment by ChenJia0212** [comment]
@ayziksha   thanks, I will try ~

**Comment by ayziksha** [comment]
OK, I'm closing the issue.
Let me know if it needs re-opening
